### ISSUE TITLE
Make schemas folder a submodule

### ISSUE THREAD

**Issue by nalgeon** [adnikiforov/iuliia-rb#1]
You might want to make `lib/schemas` folder a git submodule pointing to `https://github.com/nalgeon/iuliia` repo. This will make it easier to keep schemas up to date.

If you consider doing so:

1. Delete existing schemas folder and commit.
2. Re-add it as submodule:
```sh
git submodule add https://github.com/nalgeon/iuliia lib/schemas
```
3. Commit and push.

**Comment by adnikiforov** [comment]
That's a good idea. I'll take a look on that soon.

**Comment by adnikiforov** [comment]
Done: https://github.com/adnikiforov/iuliia-rb/commit/6378abc0f9db2a1362795ea4927aaed65e937d01
